# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/rosetta/Unreal

TARGETS = \
	FGCT4016-Android-DebugGame  \
	FGCT4016-Android-Development  \
	FGCT4016-Android-Shipping  \
	FGCT4016-Linux-DebugGame  \
	FGCT4016-Linux-Development  \
	FGCT4016-Linux-Shipping  \
	FGCT4016-LinuxArm64-DebugGame  \
	FGCT4016-LinuxArm64-Development  \
	FGCT4016-LinuxArm64-Shipping  \
	FGCT4016 \
	FGCT4016Editor-Linux-DebugGame  \
	FGCT4016Editor-Linux-Development  \
	FGCT4016Editor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend FGCT4016Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug FGCT4016Editor-Linux-Debug


FGCT4016-Android-DebugGame:
	 $(BUILD) FGCT4016 Android DebugGame  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-Android-Development:
	 $(BUILD) FGCT4016 Android Development  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-Android-Shipping:
	 $(BUILD) FGCT4016 Android Shipping  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-Linux-DebugGame:
	 $(BUILD) FGCT4016 Linux DebugGame  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-Linux-Development:
	 $(BUILD) FGCT4016 Linux Development  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-Linux-Shipping:
	 $(BUILD) FGCT4016 Linux Shipping  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-LinuxArm64-DebugGame:
	 $(BUILD) FGCT4016 LinuxArm64 DebugGame  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-LinuxArm64-Development:
	 $(BUILD) FGCT4016 LinuxArm64 Development  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016-LinuxArm64-Shipping:
	 $(BUILD) FGCT4016 LinuxArm64 Shipping  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016: FGCT4016-Linux-Development

FGCT4016Editor-Linux-DebugGame:
	 $(BUILD) FGCT4016Editor Linux DebugGame  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016Editor-Linux-Development:
	 $(BUILD) FGCT4016Editor Linux Development  -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" $(ARGS)

FGCT4016Editor: FGCT4016Editor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/rosetta/Development/FGCT4016-Gameplay-Design-and-Programming/FGCT4016/FGCT4016.uproject" -Game 

.PHONY: $(TARGETS)
